// var x =5;

// var y =6;

// var z =2.3;


// var total = x+y+z;

// var sub= x-y;

// var multi = x * y;

// var devide = x / y;

// console.log(typeof devide)

// var value =devide.toFixed(4)

// console.log(5 + number (value))

//console.log(10/3)

// var x =5;

// console.log (x * * * 3)

//modulas %



// console.log(10/2)

//10/3 bagful3,bagshesh 1



// console.log(10 % 2)


// console.log (10 % 10) = 0

// console.log (8 % 10) = 8  choto sonka hobe man


var x = 5;
//x = x+2

//x =+2;

//x=x-2;

//x -=2

//x--
//x++
console.log(x)









